# Generated by Django 5.1.7 on 2025-03-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treinos", "0003_diasemana_alter_gymprofile_altura_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaTreino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("segunda", "Segunda-feira"),
                            ("terca", "Terça-feira"),
                            ("quarta", "Quarta-feira"),
                            ("quinta", "Quinta-feira"),
                            ("sexta", "Sexta-feira"),
                            ("sabado", "Sábado"),
                            ("domingo", "Domingo"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DiaSemana",
        ),
        migrations.AlterField(
            model_name="gymprofile",
            name="dias_treino",
            field=models.ManyToManyField(blank=True, to="treinos.diatreino"),
        ),
    ]
