services:
  web:
    build:
      context: .
    #volumes:
    #  - .:/app/
    command: >
      sh -c "poetry run python manage.py migrate &&
             poetry run uvicorn gym_manager.asgi:application --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - .env  

  database:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env  
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
