# Generated by Django 5.1.7 on 2025-03-20 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Task", "verbose_name_plural": "Tasks"},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="deu_date",
            new_name="due_date",
        ),
    ]
