# Generated by Django 5.1.7 on 2025-03-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treinos", "0004_diatreino_delete_diasemana_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diatreino",
            name="dia",
        ),
        migrations.AddField(
            model_name="diatreino",
            name="nome",
            field=models.CharField(
                choices=[
                    ("segunda", "Segunda-feira"),
                    ("terca", "Terça-feira"),
                    ("quarta", "Quarta-feira"),
                    ("quinta", "Quinta-feira"),
                    ("sexta", "Sexta-feira"),
                    ("sabado", "Sábado"),
                    ("domingo", "Domingo"),
                ],
                default="segunda",
                max_length=20,
            ),
        ),
    ]
