# Generated by Django 5.1.7 on 2025-03-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treinos", "0005_remove_diatreino_dia_diatreino_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diatreino",
            name="nome",
            field=models.CharField(
                choices=[
                    ("segunda", "Segunda-feira"),
                    ("terca", "Terça-feira"),
                    ("quarta", "Quarta-feira"),
                    ("quinta", "Quinta-feira"),
                    ("sexta", "Sexta-feira"),
                    ("sabado", "Sábado"),
                    ("domingo", "Domingo"),
                ],
                max_length=20,
            ),
        ),
    ]
