# Generated by Django 5.1.7 on 2025-03-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treinos", "0007_alter_gymprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gymprofile",
            name="dias_treino",
        ),
        migrations.DeleteModel(
            name="DiaTreino",
        ),
        migrations.AddField(
            model_name="gymprofile",
            name="dias_treino",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2_3", "2-3 dias por semana"),
                    ("3_4", "3-4 dias por semana"),
                    ("4_5", "4-5 dias por semana"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
